// Short form-cue descriptions, shown in the exercise detail sheet.
const INFO: Record<string, string> = {
  'bench-press': 'Lie on a flat bench, grip slightly wider than shoulders. Lower the bar to mid-chest with elbows ~45°, then press up until arms lock out. Keep shoulder blades pinched and feet planted.',
  'incline-bench-press': 'Set the bench to 30–45°. Lower the bar to your upper chest and press up and slightly back. Hits the upper pecs and front delts.',
  'db-bench-press': 'Press two dumbbells from chest level until arms are extended. Greater range of motion than the barbell; keep the weights stable and wrists straight.',
  'db-incline-press': 'On a 30–45° incline bench, press dumbbells from shoulder level to lockout. Lower with control until you feel a stretch across the upper chest.',
  'chest-fly': 'Lie flat with dumbbells over your chest, slight elbow bend. Open your arms in a wide arc until you feel a chest stretch, then squeeze back together.',
  'cable-fly': 'Stand between cable stacks, handles at chest height. Bring your hands together in front of you in a hugging arc, squeezing the chest at the midpoint.',
  'push-up': 'Hands under shoulders, body in a straight line. Lower your chest to just above the floor and press back up. Brace your core throughout.',
  'dips': 'Support yourself on parallel bars, lean slightly forward. Lower until shoulders dip below elbows, then press back up. Lean forward for chest, stay upright for triceps.',
  'machine-chest-press': 'Adjust the seat so handles sit at mid-chest. Press forward to full extension without locking elbows hard, then return with control.',
  'deadlift': 'Stand with mid-foot under the bar. Hinge, grip, brace, and stand up by driving through your heels, keeping the bar against your legs and back flat.',
  'barbell-row': 'Hinge to ~45°, back flat. Pull the bar to your lower ribs, squeezing the shoulder blades, then lower under control. No torso heave.',
  'pull-up': 'Hang from a bar with an overhand grip. Pull until your chin clears the bar, leading with the chest, then lower fully. Add weight when bodyweight gets easy.',
  'chin-up': 'Underhand grip, shoulder width. Pull your chin over the bar; biceps work harder than in a pull-up. Full hang at the bottom of every rep.',
  'lat-pulldown': 'Grip wide, lean back slightly. Pull the bar to your upper chest while driving elbows down, then let the lats stretch fully at the top.',
  'seated-row': 'Sit tall, pull the handle to your stomach with elbows close, squeezing your mid-back. Let your shoulders protract forward on the return.',
  'db-row': 'One hand and knee on a bench, back flat. Row the dumbbell to your hip, keeping the elbow close, and lower with a full lat stretch.',
  't-bar-row': 'Straddle the bar, hinge forward, and row the load to your chest. Keep the lower back neutral and squeeze at the top.',
  'rack-pull': 'A deadlift from knee height in a rack. Overloads the top half of the pull — keep lats tight and finish tall with glutes.',
  'overhead-press': 'Stand tall, bar at your collarbone. Press straight up, moving your head back then through, and lock out overhead. Squeeze glutes to protect your back.',
  'db-shoulder-press': 'Seated or standing, press dumbbells from shoulder height to overhead lockout. Lower until elbows reach ~90°.',
  'lateral-raise': 'Raise dumbbells out to your sides with soft elbows until arms are parallel to the floor. Lead with the elbows; no swinging.',
  'front-raise': 'Raise a dumbbell straight in front of you to shoulder height with a neutral spine. Lower slowly. Targets the front delts.',
  'rear-delt-fly': 'Hinge forward, arms hanging. Open your arms wide, squeezing the rear delts and upper back at the top.',
  'face-pull': 'Set a rope at face height. Pull toward your face while pulling the rope apart, ending with knuckles by your ears. Great for posture and rear delts.',
  'arnold-press': 'Start with palms facing you at shoulder height. Rotate outward as you press overhead, finishing palms-forward. Smooth, controlled rotation.',
  'upright-row': 'Pull the bar up along your body to chest height, elbows leading. Keep the grip a bit wider to stay friendly on the shoulders.',
  'barbell-curl': 'Stand tall, elbows pinned to your sides. Curl the bar to shoulder height and lower slowly. No swinging from the hips.',
  'db-curl': 'Curl dumbbells with palms up, one or both arms. Keep elbows still and squeeze at the top; control the negative.',
  'hammer-curl': 'Curl with a neutral (thumbs-up) grip. Hits the brachialis and forearms; keep wrists locked.',
  'preacher-curl': 'Arms on the preacher pad, curl to the top and lower until arms are almost straight. The pad removes all cheating.',
  'cable-curl': 'Curl a cable bar or rope with constant tension. Step back slightly so the stack never rests between reps.',
  'incline-db-curl': 'Lie back on an incline bench, arms hanging behind your torso. Curl from a deep stretch — brutal but effective for the long head.',
  'close-grip-bench': 'Bench press with hands shoulder-width. Keep elbows tucked and press through the triceps. Touch lower on the chest.',
  'tricep-pushdown': 'Elbows pinned at your sides, press the cable down to full lockout and squeeze. Only the forearms move.',
  'skullcrusher': 'Lying down, lower the bar to your forehead (or just behind) by bending only the elbows, then extend back up.',
  'overhead-tricep-ext': 'Hold a dumbbell overhead with both hands. Lower it behind your head, then extend to lockout. Keep elbows pointed forward.',
  'tricep-dip': 'Hands on a bench behind you, legs extended. Lower your hips by bending the elbows to ~90°, then press up.',
  'squat': 'Bar on your upper back, feet shoulder-width. Sit down between your hips until thighs are at least parallel, then drive up through mid-foot. Brace hard.',
  'front-squat': 'Bar racked on the front delts, elbows high. Squat deep while staying upright. Builds quads and demands a strong core.',
  'leg-press': 'Feet shoulder-width on the platform. Lower until knees reach ~90° or slightly deeper, then press without locking out the knees.',
  'leg-extension': 'Extend your knees against the pad until legs are straight, squeeze the quads, and lower slowly.',
  'goblet-squat': 'Hold a dumbbell at your chest and squat between your heels. Excellent squat-pattern teacher and quad builder.',
  'bulgarian-split-squat': 'Rear foot elevated on a bench, front foot forward. Lower straight down until the rear knee nears the floor. Brutal single-leg strength.',
  'lunge': 'Step forward and lower until both knees hit ~90°. Push off the front heel to return. Keep your torso tall.',
  'hack-squat': 'Back against the machine pad, squat down deep and drive up through the whole foot. Quad-focused with the back supported.',
  'romanian-deadlift': 'From standing, hinge at the hips with soft knees, sliding the bar down your thighs until your hamstrings stretch hard, then squeeze back up.',
  'leg-curl': 'Curl your heels toward your glutes against the pad and lower slowly. Strict and controlled — no bouncing.',
  'good-morning': 'Bar on your back, hinge forward to ~45° with a flat back, then extend back up using hamstrings and glutes. Stay light and strict.',
  'db-rdl': 'Romanian deadlift holding dumbbells. Hinge until you feel the hamstring stretch, keeping the weights close to your legs.',
  'hip-thrust': 'Upper back on a bench, bar over your hips. Drive your hips up to full extension and squeeze the glutes hard at the top.',
  'glute-kickback': 'With a cable cuff at your ankle, kick one leg straight back, squeezing the glute. Keep your torso still.',
  'sumo-deadlift': 'Wide stance, toes out, grip inside the knees. Push the floor apart as you stand. More glutes and adductors than conventional.',
  'calf-raise': 'Rise onto your toes through a full range, pause at the top, and lower until you feel a deep calf stretch.',
  'seated-calf-raise': 'Seated with pads on your knees, raise your heels. Targets the soleus — use a slow, full range.',
  'plank': 'Forearms down, body in a rigid straight line. Squeeze glutes and abs; do not let the hips sag. Hold for time.',
  'crunch': 'Curl your shoulder blades off the floor, exhaling as you squeeze the abs. Lower with control — short range, high tension.',
  'hanging-leg-raise': 'Hanging from a bar, raise your legs to horizontal (or knees to chest) without swinging. Control the descent.',
  'cable-crunch': 'Kneel below a rope attachment and crunch your elbows toward your knees, flexing the spine against the cable.',
  'russian-twist': 'Seated, lean back slightly, rotate your torso side to side. Add weight for difficulty; move from the trunk, not the arms.',
  'ab-wheel': 'Kneel, roll the wheel forward as far as you can keep a flat back, then pull back with your abs and lats.',
  'clean-and-press': 'Explosively pull the bar from the floor to your shoulders, then press overhead. Power, coordination, and full-body strength.',
  'kettlebell-swing': 'Hinge and snap your hips forward to swing the bell to chest height. The arms are just hooks — power comes from the hips.',
  'farmers-walk': 'Pick up heavy dumbbells and walk tall with quick steps. Grip, traps, and core all under load.',
  'burpee': 'Squat, kick back to a push-up, jump back in, and leap. Full-body conditioning at its most honest.',
  'rowing-machine': 'Drive with the legs, then lean back and pull the handle to your ribs. Legs–back–arms on the way out, reverse on the way in.',
}

export function exerciseInfo(id: string): string {
  return INFO[id] ?? 'Perform the movement through a full range of motion with controlled tempo and strict form.'
}
